apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name:  sync-job-wt
spec:
  serviceAccountName: pipeline
  templates:
    - name: SyncDocumentsByType
      inputs:
        parameters:
        - name: THOTH_DOCUMENT_TYPE
          description: The type of document to be synced that the workflowTemplate will be invoked with.
          enum:
            - "adviser"
            - "solver"
            - "revsolver"
            - "package-extract"
            - "provenance-checker"
            - "security-indicator"
        - name: THOTH_SYNC_FORCE
          default: "0"
        - name: THOTH_SYNC_GRACEFUL
          default: "0"
        - name: THOTH_SYNC_DEBUG
          default: "0"
      container:
        image: "quay.io/thoth-station/sync-job:v0.2.4"
        env:
          - name: "THOTH_SYNC_FORCE"
            value: "0"
          - name: "THOTH_SYNC_GRACEFUL"
            value: "0"
          - name: THOTH_SYNC_DEBUG
            value: "0"
          - name: THOTH_LOG_SYNC
            value: "INFO"
          - name: THOTH_DOCUMENT_TYPE
            value: "{{inputs.parameters.THOTH_DOCUMENT_TYPE}}"
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                key: deployment-name
                name: thoth
          - name: THOTH_S3_ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                key: host
                name: ceph
          - name: THOTH_CEPH_BUCKET
            valueFrom:
              configMapKeyRef:
                key: bucket-name
                name: ceph
          - name: THOTH_CEPH_BUCKET_PREFIX
            valueFrom:
              configMapKeyRef:
                key: bucket-prefix
                name: ceph
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                key: storage-bucket-name
                name: thoth
          - name: THOTH_CEPH_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ceph
                key: key-id
          - name: THOTH_CEPH_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ceph
                key: secret-key
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: thoth
                key: sentry-dsn
          - name: KNOWLEDGE_GRAPH_HOST
            valueFrom:
              configMapKeyRef:
                key: postgresql-host
                name: thoth
          - name: KNOWLEDGE_GRAPH_PORT
            value: "5432"
          - name: KNOWLEDGE_GRAPH_SSL_DISABLED
            value: "1"
          - name: KNOWLEDGE_GRAPH_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
          - name: KNOWLEDGE_GRAPH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
          - name: KNOWLEDGE_GRAPH_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name
          - name: PROMETHEUS_PUSHGATEWAY_URL
            valueFrom:
              configMapKeyRef:
                name: prometheus
                key: pushgateway-url
        resources:
          limits:
            memory: "2Gi"
            cpu: 4
          requests:
            memory: "2Gi"
            cpu: 4
